name: G9 Designs
favicon: null
layout_spectrum: 0.5
typography_spectrum: 0.488176
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d3e1e7'
    - '#4a3c55'
    - '#33a5d7'
    - '#00ffff'
    - '#0000ff'
  brandStrength: 0.134291
  lightness: 0.146115
  saturation: 0.133446
  rhythmicContrast: 0.494088
purpose:
  - name: null
    item: null
    url: null
