analytics: {}
color:
  brandColors:
    - '#d3e1e7'
    - '#4a3c55'
    - '#33a5d7'
    - '#00ffff'
    - '#0000ff'
  brandStrength: 0.821791
  lightness: 0.625
  rhythmicContrast: 0.109797
  saturation: 0.892736
cta: {}
layout_spectrum: 1
name: G9 Designs
opengraph: {}
purpose:
  - {}
typography_spectrum: 0.488176
