name: G9 Designs
favicon: null
layout_spectrum: 0
typography_spectrum: 0.488176
title: G9 Designs
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8125
  lightness: 0.3125
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose:
  - name: null
    item: null
    url: null
