analytics: {}
color:
  brandColors:
    - '#d3e1e7'
    - '#4a3c55'
    - '#33a5d7'
    - '#00ffff'
    - '#0000ff'
  brandStrength: 0.134291
  lightness: 0.146115
  rhythmicContrast: 0.494088
  saturation: 0.133446
cta: {}
layout_spectrum: 0
name: G9 Designs
opengraph: {}
purpose:
  - {}
typography_spectrum: 0.488176
